(ns crypto-analysis.core-test
  (:require [clojure.test :refer :all]
            [crypto-analysis.core :refer :all]))

(deftest caesar-chi-sq-test
  (testing "Chi squared attack to Caesar"
    (is (= (caesar-chi-sq "AZOQGBAZMYUPZUSTFPDQMDKITUXQUBAZPQDQPIQMWMZPIQMDKAHQDYMZKMCGMUZFMZPOGDUAGEHAXGYQARRADSAFFQZXADQITUXQUZAPPQPZQMDXKZMBBUZSEGPPQZXKFTQDQOMYQMFMBBUZSMEAREAYQAZQSQZFXKDMBBUZSDMBBUZSMFYKOTMYNQDPAADFUEEAYQHUEUFADUYGFFQDQPFMBBUZSMFYKOTMYNQDPAADAZXKFTUEMZPZAFTUZSYADQ") "ONCEUPONAMIDNIGHTDREARYWHILEIPONDEREDWEAKANDWEARYOVERMANYAQUAINTANDCURIOUSVOLUMEOFFORGOTTENLOREWHILEINODDEDNEARLYNAPPINGSUDDENLYTHERECAMEATAPPINGASOFSOMEONEGENTLYRAPPINGRAPPINGATMYCHAMBERDOORTISSOMEVISITORIMUTTEREDTAPPINGATMYCHAMBERDOORONLYTHISANDNOTHINGMORE"))
    (is (= (caesar-chi-sq "KYVEVOKDVJJRXVNZCCSVVETIPGKVULJZEXKYVGRXVKYIVVYLEUIVUREUVZXYKPJVMVEFWKYVTFLEKFWDFEKVTYIZJKF") "THENEXTMESSAGEWILLBEENCRYPTEDUSINGTHEPAGETHREEHUNDREDANDEIGHTYSEVENOFTHECOUNTOFMONTECHRISTO"))
    ))
